### ISSUE TITLE
uninitialized constant Hook::MethodDecorator

### ISSUE THREAD

**Issue by afeld** [moonmaster9000/hook#1]
Hey! I was trying to use [specdown](https://github.com/moonmaster9000/specdown) for a new little project, but got this error when running it on [the README](https://github.com/afeld/compare_by/blob/d5153bad3ca2f6dcdb9921ffb482dfa741053aec/README.md):

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ specdown README.md
/Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/hook-0.1.0/lib/hook.rb:9:in `<module:Hook>': uninitialized constant Hook::MethodDecorator (NameError)
Did you mean?  MethodDecorators
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/hook-0.1.0/lib/hook.rb:3:in `<top (required)>'
    from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/specdown-0.5.1/lib/specdown.rb:5:in `<top (required)>'
    from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/specdown-0.5.1/bin/specdown:2:in `<top (required)>'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/specdown:22:in `load'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/specdown:22:in `<main>'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by moonmaster9000** [comment]
Hmmm... I haven't looked at this project in years... I'm afraid to look at
the code now!

On Sat, Apr 23, 2016 at 6:11 PM, Aidan Feldman notifications@github.com
wrote:

> Hey! I was trying to use specdown
> https://github.com/moonmaster9000/specdown for a new little project,
> but got this error when running it on the README
> https://github.com/afeld/compare_by/blob/d5153bad3ca2f6dcdb9921ffb482dfa741053aec/README.md
> :
> 
> $ ruby -v
> ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
> $ specdown README.md
> /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/hook-0.1.0/lib/hook.rb:9:in `<module:Hook>': uninitialized constant Hook::MethodDecorator (NameError)
> Did you mean?  MethodDecorators
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/hook-0.1.0/lib/hook.rb:3:in`<top (required)>'
>     from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/specdown-0.5.1/lib/specdown.rb:5:in `<top (required)>'
>     from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>     from /Users/aidanfeldman/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/specdown-0.5.1/bin/specdown:2:in`<top (required)>'
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/specdown:22:in `load'
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/specdown:22:in`<main>'
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
>     from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`<main>'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/moonmaster9000/hook/issues/1

## 

Parker Matthew
Associate Director of Engineering
Pivotal Labs, NY
mparker@pivotal.io
